/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaegerfuchsspiel;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Name
 */
public class Demo2D extends javax.swing.JPanel {

    Spieler[] alleBeteiligten = new Spieler[2];
    Fuchs derFuchs;
    Jaeger derJaeger;
    Timer t;
    public Demo2D() {
        initComponents();
        setSize(1000, 1000);
        derFuchs = new Fuchs(getWidth(), getHeight());
        derJaeger = new Jaeger(getWidth(), getHeight());
        derFuchs.setJaeger(derJaeger);
        derFuchs.erzeugeStartPositionen();
        derJaeger.setFuchs(derFuchs);
        alleBeteiligten[0] = derFuchs;
        alleBeteiligten[1] = derJaeger;
        t = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                naechsteRunde();
            }
        });
        t.start();
    }

    public void naechsteRunde() {
        for (int i = 0; i < alleBeteiligten.length; i++) {
            alleBeteiligten[i].aenderePosition();
        }
        repaint();
        if(derJaeger.isCatched()){
        t.stop();
        }
    }

    public void paintComponent(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, 1100, 1100);
        g.setColor(Color.BLACK);
        g.drawRect(0, 0, 1100, 1100);
        g.drawImage(alleBeteiligten[0].gibBild(), alleBeteiligten[0].gibX(), alleBeteiligten[0].gibY(), null);
        g.drawImage(alleBeteiligten[1].gibBild(), alleBeteiligten[1].gibX(), alleBeteiligten[1].gibY(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
